### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by johnnychen94** [JuliaCN/LeetCode.jl#43]
#36 #42 have brought up the documentation for this repo, which is awesome.

We still have something that needs to do to improve its usability:

- [ ] hide the solutions by default
- [ ] category-based and/or difficulty-based filters to better organize the documentation. This requires our problems indices shown on a new page, instead of on the sidebar. Hence a new democard theme is required here. (mid/long-term)

**Comment by rfhklwt** [comment]
我试验了一下:

- 通过在`docs/build/assets/themes`下的两个css文件的末尾加上如下语句：

```css
.none {
  color: transparent;
  text-shadow: 3px 3px 15px rgba(0, 0, 0, 1);
}.none .hljs-comment,
.none .hljs-built_in,
.none .hljs-meta,
.none .hljs-keyword,
.none .hljs-comment,
.none .hljs-string,
.none .hljs-literal,.none .hljs-number {  color: transparent;}
```
- 接着在`docs/build/assets`里的`documenter.js`的末尾添加鼠标动作代码，如下：
```js
let code = document.getElementsByClassName('language-julia')[0];
code.classList.add('none');
code.addEventListener('mouseover', function () {
  code.classList.remove('none');
});
code.addEventListener('mouseout', function () {
  code.classList.add('none');
});
```
就可以实现代码隐藏了，当鼠标没在代码框的时候，是这样的：
![image](https://user-images.githubusercontent.com/41724569/101483770-9eac4d80-3993-11eb-8d21-67e2fbf5edff.png)
当鼠标移到代码框的时候，就会显示代码：
![image](https://user-images.githubusercontent.com/41724569/101483796-a835b580-3993-11eb-8f8c-40351e78deb9.png)

## 问题：
- 一开始我打算在`make.jl`里对渲染文档生成的`css`文件和`documenter.jl`文件进行代码的补充的，将代码放置在`makedocs`之后，这个应该是没啥问题的把。`github`的临时文件的销毁应该是在这之后把？
![image](https://user-images.githubusercontent.com/41724569/101483695-82101580-3993-11eb-82c4-de4a21d940be.png)
- 照着这个思路然后发现在写入`css`时失败了，`documenter.js`成功。这是由于`css`在生成的时候是以只读文件的形式，所以无法写入。
- 因此，可能需要你那边把`css`手动添加一下代码？或者去掉只读之类的，上面`css`代码是一个新样式，用于使字符模糊化的样式，因此不会影响到其他的。 @johnnychen94
